// LegitImage backend proxy — Cloudflare Worker
//
// Stands between the iOS app and the third-party detection APIs so the
// vendor keys never ship in the app bundle. Two routes the app calls:
//
//   POST /synthid       → proxies to Vertex AI's image-verification model
//   POST /sightengine   → proxies to Sightengine's check.json endpoint
//
// Each accepts a multipart body with two fields:
//   image   — the image bytes
//   source  — "fileUpload" | "screenshot"
//
// And returns a normalized payload:
//   { verdict: "ai_generated"|"real"|"uncertain",
//     confidence: 0..1,
//     explanation: "…plain English sentence…" }
//
// Required environment variables (set via `wrangler secret put …`):
//   APP_TOKEN              — optional shared secret the app sends in Authorization
//   SIGHTENGINE_USER       — Sightengine API user id
//   SIGHTENGINE_SECRET     — Sightengine API secret
//   GCP_PROJECT_ID         — Google Cloud project id
//   GCP_LOCATION           — Vertex AI region (e.g. "us-central1")
//   GCP_ACCESS_TOKEN       — short-lived OAuth access token (rotate via service account)
//
// See Backend/README.md for deploy steps.

export default {
    async fetch(request, env) {
        const url = new URL(request.url);

        // Auth gate. Only enforce when APP_TOKEN is configured — that
        // way the worker is usable for local dev without setting it.
        if (env.APP_TOKEN) {
            const header = request.headers.get("Authorization") || "";
            if (header !== `Bearer ${env.APP_TOKEN}`) {
                return json({ error: "unauthorized" }, 401);
            }
        }

        if (request.method !== "POST") {
            return json({ error: "method_not_allowed" }, 405);
        }

        try {
            const form = await request.formData();
            const imageFile = form.get("image");
            const source = form.get("source") || "fileUpload";
            if (!imageFile || typeof imageFile === "string") {
                return json({ error: "missing_image" }, 400);
            }
            const imageBytes = new Uint8Array(await imageFile.arrayBuffer());

            switch (url.pathname.replace(/\/+$/, "")) {
                case "/synthid":
                    return await callSynthID(imageBytes, source, env);
                case "/sightengine":
                    return await callSightengine(imageBytes, source, env);
                default:
                    return json({ error: "not_found" }, 404);
            }
        } catch (err) {
            return json({ error: "internal_error", message: String(err) }, 500);
        }
    },
};

// ─────────────────────────────────────────────────────────────────────
// SynthID via Vertex AI

async function callSynthID(imageBytes, _source, env) {
    const endpoint = `https://${env.GCP_LOCATION}-aiplatform.googleapis.com/v1/projects/${env.GCP_PROJECT_ID}/locations/${env.GCP_LOCATION}/publishers/google/models/image-verification:predict`;

    const body = {
        instances: [{ image: { bytesBase64Encoded: base64(imageBytes) } }],
        parameters: { watermarkVerification: true },
    };

    const res = await fetch(endpoint, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${env.GCP_ACCESS_TOKEN}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify(body),
    });

    if (!res.ok) {
        const text = await res.text();
        return json({ error: "vertex_error", status: res.status, message: text }, 502);
    }

    const data = await res.json();
    const prediction = (data.predictions || [])[0] || {};
    const decision = (prediction.decision || "").toLowerCase();

    let verdict = "uncertain";
    let explanation = "SynthID result was inconclusive.";
    if (decision.includes("no_watermark") || decision === "not_detected") {
        verdict = "real";
        explanation = "No SynthID watermark detected. Only Google-generated images carry SynthID, so this isn't proof of authenticity.";
    } else if (decision.includes("detected")) {
        verdict = "ai_generated";
        explanation = "SynthID watermark detected — image was generated by a Google model (Gemini / Imagen).";
    }

    return json({
        verdict,
        confidence: prediction.confidence ?? null,
        explanation,
    });
}

// ─────────────────────────────────────────────────────────────────────
// Sightengine

async function callSightengine(imageBytes, _source, env) {
    const form = new FormData();
    form.append("media", new Blob([imageBytes]), "image");
    form.append("models", "genai,properties");
    form.append("api_user", env.SIGHTENGINE_USER);
    form.append("api_secret", env.SIGHTENGINE_SECRET);

    const res = await fetch("https://api.sightengine.com/1.0/check.json", {
        method: "POST",
        body: form,
    });

    if (!res.ok) {
        const text = await res.text();
        return json({ error: "sightengine_error", status: res.status, message: text }, 502);
    }

    const data = await res.json();
    if (data.error) {
        return json({ error: "sightengine_api_error", message: data.error.message }, 502);
    }

    const score = data.type?.ai_generated;
    if (typeof score !== "number") {
        return json({
            verdict: "uncertain",
            confidence: 0.2,
            explanation: "Sightengine returned no AI-pattern score for this image.",
        });
    }

    let verdict = "uncertain";
    if (score >= 0.7) verdict = "ai_generated";
    else if (score < 0.3) verdict = "real";

    const percent = Math.round(score * 100);
    let explanation = `Visual pattern analysis: ${percent}% likelihood of AI generation.`;

    const age = data.faces?.[0]?.attributes?.age?.value;
    if (typeof age === "number") {
        explanation += ` Detected face age estimate: ~${Math.round(age)} years.`;
    }

    return json({
        verdict,
        confidence: score < 0.5 ? 1 - score : score,
        explanation,
    });
}

// ─────────────────────────────────────────────────────────────────────
// Helpers

function json(body, status = 200) {
    return new Response(JSON.stringify(body), {
        status,
        headers: { "Content-Type": "application/json" },
    });
}

function base64(bytes) {
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
        binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
}
