//
//  SynthIDDetector.swift
//  LegitImage
//
//  Calls Google Cloud Vertex AI's SynthID detection endpoint. Sends the
//  image bytes as base64 in the predict payload and parses the
//  prediction back into a CheckResult.
//
//  Endpoint shape:
//    POST https://{region}-aiplatform.googleapis.com/v1/projects/{p}/locations/{r}/publishers/google/models/image-verification:predict
//    Authorization: Bearer <access token>
//    {
//      "instances": [{
//        "image": { "bytesBase64Encoded": "<base64>" }
//      }],
//      "parameters": { "watermarkVerification": true }
//    }
//

import Foundation

struct SynthIDDetector: Detector {
    let kind: CheckKind = .synthID
    let session: URLSession

    init(session: URLSession = .shared) {
        self.session = session
    }

    func run(on input: ImageInput) async -> CheckResult {
        guard APIConfig.Features.synthIDEnabled else {
            return .skipped(kind, reason: "SynthID check is disabled in configuration.")
        }
        guard APIConfig.isSynthIDConfigured else {
            return .skipped(kind, reason: "SynthID is not configured. Add a Vertex AI project + token to APIConfig.")
        }

        do {
            let response = try await callVertexAI(data: input.data)
            return interpret(response, source: input.source)
        } catch {
            return .failed(kind, message: error.localizedDescription)
        }
    }

    // MARK: - Network

    private struct PredictRequest: Encodable {
        struct Instance: Encodable {
            struct Image: Encodable { let bytesBase64Encoded: String }
            let image: Image
        }
        struct Parameters: Encodable { let watermarkVerification: Bool }
        let instances: [Instance]
        let parameters: Parameters
    }

    private struct PredictResponse: Decodable {
        struct Prediction: Decodable {
            /// Vertex returns a string label such as "watermark_detected" /
            /// "no_watermark_detected" / "unknown_watermark". We decode
            /// permissively because the exact wording shifts across
            /// releases.
            let decision: String?
            let confidence: Double?
        }
        let predictions: [Prediction]
    }

    private func callVertexAI(data: Data) async throws -> PredictResponse {
        var request = URLRequest(url: APIConfig.SynthID.endpoint)
        request.httpMethod = "POST"
        request.setValue("Bearer \(APIConfig.SynthID.accessToken)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")

        let body = PredictRequest(
            instances: [.init(image: .init(bytesBase64Encoded: data.base64EncodedString()))],
            parameters: .init(watermarkVerification: true)
        )
        request.httpBody = try JSONEncoder().encode(body)

        let (responseData, urlResponse) = try await session.data(for: request)
        guard let http = urlResponse as? HTTPURLResponse else {
            throw URLError(.badServerResponse)
        }
        guard (200..<300).contains(http.statusCode) else {
            let message = String(data: responseData, encoding: .utf8) ?? "HTTP \(http.statusCode)"
            throw SynthIDError.requestFailed(status: http.statusCode, message: message)
        }
        return try JSONDecoder().decode(PredictResponse.self, from: responseData)
    }

    // MARK: - Interpretation

    private func interpret(_ response: PredictResponse, source: ImageSource) -> CheckResult {
        guard let prediction = response.predictions.first else {
            return CheckResult(
                kind: kind,
                status: .completed(verdict: .uncertain),
                explanation: "SynthID returned no predictions for this image.",
                confidence: 0.2
            )
        }

        let decision = (prediction.decision ?? "").lowercased()
        let verdict: CheckVerdict
        let phrase: String

        if decision.contains("watermark_detected") || decision.contains("detected") && !decision.contains("no") {
            verdict = .aiGenerated
            phrase = "SynthID watermark detected — image was generated by a Google model (Gemini / Imagen)."
        } else if decision.contains("no_watermark") || decision == "not_detected" {
            verdict = .real
            phrase = "No SynthID watermark detected. Note: only Google-generated images carry SynthID."
        } else {
            verdict = .uncertain
            phrase = "SynthID result was inconclusive (\(decision.isEmpty ? "unknown" : decision))."
        }

        if !source.synthIDIsReliable {
            return CheckResult(
                kind: kind,
                status: .unreliable(verdict: verdict, reason: "Screenshots can damage watermarks; treat as low signal."),
                explanation: phrase,
                confidence: (prediction.confidence ?? 0.5) * 0.3
            )
        }

        return CheckResult(
            kind: kind,
            status: .completed(verdict: verdict),
            explanation: phrase,
            confidence: prediction.confidence ?? 0.6
        )
    }
}

enum SynthIDError: LocalizedError {
    case requestFailed(status: Int, message: String)

    var errorDescription: String? {
        switch self {
        case .requestFailed(let status, let message):
            return "SynthID request failed (\(status)): \(message)"
        }
    }
}
